-- MySQL Script generated by MySQL Workbench
-- Thu Oct 24 19:18:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tiendamultimedia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tiendamultimedia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tiendamultimedia` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `tiendamultimedia` ;

-- -----------------------------------------------------
-- Table `tiendamultimedia`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`administrador` (
  `id_administrador` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `contrasena` VARCHAR(45) NOT NULL,
  `nickname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_administrador`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendamultimedia`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`categoria` (
  `id_categoria` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendamultimedia`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`usuario` (
  `id_usuario` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `apellido` VARCHAR(45) NULL DEFAULT NULL,
  `contrasena` VARCHAR(45) NULL DEFAULT NULL,
  `correo` VARCHAR(45) NULL DEFAULT NULL,
  `avatar` LONGBLOB NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `direccion` VARCHAR(70) NULL DEFAULT NULL,
  `nickname` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendamultimedia`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`producto` (
  `id_producto` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre_producto` VARCHAR(45) NULL DEFAULT NULL,
  `descripcion` VARCHAR(140) NULL DEFAULT NULL,
  `video` VARCHAR(244) NULL DEFAULT NULL,
  `visitado` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `buscado` SMALLINT(5) UNSIGNED NULL DEFAULT NULL,
  `stock` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `promedio_valoracion` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  `bandera_activo` BIT(1) NULL DEFAULT NULL,
  `id_administrador` SMALLINT(5) UNSIGNED NOT NULL,
  `fecha_publicacion` DATE NULL DEFAULT NULL,
  `id_categoria` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_producto`),
  INDEX `id_administrador` (`id_administrador` ASC) VISIBLE,
  INDEX `id_categoria` (`id_categoria` ASC) VISIBLE,
  CONSTRAINT `producto_ibfk_1`
    FOREIGN KEY (`id_administrador`)
    REFERENCES `tiendamultimedia`.`administrador` (`id_administrador`),
  CONSTRAINT `producto_ibfk_2`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `tiendamultimedia`.`categoria` (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendamultimedia`.`comentario_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`comentario_producto` (
  `id_comentario` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_usuario` SMALLINT(5) UNSIGNED NOT NULL,
  `id_producto` SMALLINT(5) UNSIGNED NOT NULL,
  `comentario` VARCHAR(120) NULL DEFAULT NULL,
  PRIMARY KEY (`id_comentario`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `comentario_producto_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tiendamultimedia`.`usuario` (`id_usuario`),
  CONSTRAINT `comentario_producto_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tiendamultimedia`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendamultimedia`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`compra` (
  `id_compra` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_compra` DATE NULL DEFAULT NULL,
  `estatus` VARCHAR(10) NULL DEFAULT NULL,
  `precio` DECIMAL(15,2) NULL DEFAULT NULL,
  `id_usuario` SMALLINT(5) UNSIGNED NOT NULL,
  `id_producto` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_compra`),
  INDEX `id_usuario` (`id_usuario` ASC) VISIBLE,
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `compra_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tiendamultimedia`.`usuario` (`id_usuario`),
  CONSTRAINT `compra_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tiendamultimedia`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendamultimedia`.`imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`imagen` (
  `id_imagen` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `imagen` LONGBLOB NULL DEFAULT NULL,
  `id_producto` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_imagen`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `imagen_ibfk_1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tiendamultimedia`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendamultimedia`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`mensaje` (
  `id_mensaje` SMALLINT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `fecha_mensaje` DATE NULL DEFAULT NULL,
  `mensaje` VARCHAR(120) NULL DEFAULT NULL,
  `bandera_usuario` BIT(1) NULL DEFAULT NULL,
  `id_compra` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id_mensaje`),
  INDEX `id_compra` (`id_compra` ASC) VISIBLE,
  CONSTRAINT `mensaje_ibfk_1`
    FOREIGN KEY (`id_compra`)
    REFERENCES `tiendamultimedia`.`compra` (`id_compra`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `tiendamultimedia`.`valoracion_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tiendamultimedia`.`valoracion_producto` (
  `id_usuario` SMALLINT(5) UNSIGNED NOT NULL,
  `id_producto` SMALLINT(5) UNSIGNED NOT NULL,
  `valor` TINYINT(3) UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`, `id_producto`),
  INDEX `id_producto` (`id_producto` ASC) VISIBLE,
  CONSTRAINT `valoracion_producto_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `tiendamultimedia`.`usuario` (`id_usuario`),
  CONSTRAINT `valoracion_producto_ibfk_2`
    FOREIGN KEY (`id_producto`)
    REFERENCES `tiendamultimedia`.`producto` (`id_producto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
